version: "2.4.1"
services:
  app:
    build:
      context: .
    volumes:
      - .:/react_quiz
    ports:
      - 3000:3000
    image: app:react
    container_name: react_container
    command: npm start